### ISSUE TITLE
Slicer API documentation is not up-to-date

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#4906]
Slicer API documentation has not been updated since January.

See footer of any documentation page, for example [this](http://apidocs.slicer.org/master/classvtkMRMLSegmentEditorNode.html#a451836bc25febd5d1101f0c09ae6a558): `Generated on Thu Jan 30 2020 21:22:17 for Slicer by   doxygen 1.8.14`

**Comment by lassoan** [comment]
@jcfr or @sjh26 it would be great if you could look into this. Thanks!

**Comment by sjh26** [comment]
The apidocs generation apparently has not been running, and before that was having issues with installing dependencies for the doc builder:

https://circleci.com/gh/Slicer/apidocs.slicer.org

**Comment by lassoan** [comment]
Is there any update on this? Could the documentation generation re-enabled?

**Comment by jcfr** [comment]
This is now fixed for the latest api docs:

![image](https://user-images.githubusercontent.com/219043/92275834-dc459a00-eebd-11ea-9b4c-db30ac299147.png)

See https://apidocs.slicer.org/master/

![image](https://user-images.githubusercontent.com/219043/92275872-ed8ea680-eebd-11ea-93d9-35783c1e3146.png)

Let's keep the issue open as we still need to fix:
- versionning of doxygen documentation when a tag is pushed
- generation of review doxygen (like we do for readthedocs ...)

**Comment by jamesobutler** [comment]
Is API documentation building broken again? It is showing as Feb 19 2021 at http://apidocs.slicer.org/master/
![4785F4B5-A755-4CF3-9A43-0AE599C30546](https://user-images.githubusercontent.com/15837524/126422404-00d59b3b-17c7-4117-9d38-6192033c552b.jpeg)

**Comment by jcfr** [comment]
Thanks for the ping. I will follow up with the comments and/or PR. I have an idea of the problem.

**Comment by jamesobutler** [comment]
I've begun to investigate and have started with issuing https://github.com/Slicer/apidocs.slicer.org/pull/1

**Comment by jcfr** [comment]
Thanks @jamesobutler  I created an issue with some suggestion to move forward: https://github.com/Slicer/apidocs.slicer.org/issues/2

**Comment by jcfr** [comment]
Error related to `slicer-apidocs-builder` is now fixed in https://github.com/Slicer/slicer-apidocs-builder/pull/1

![image](https://user-images.githubusercontent.com/219043/144493516-0039b3c1-1306-40f1-9af9-362dfb19dbf7.png)

References:
* https://app.circleci.com/pipelines/github/Slicer/apidocs.slicer.org/2410/workflows/541afa8b-4645-4e76-8391-d86ce05cd28b/jobs/6740

**Comment by jcfr** [comment]
Closing. Documentation is not updated.
See https://apidocs.slicer.org/master/index.html

```
Generated on Thu Dec 2 2021 20:03:38
```

**Comment by jamesobutler** [comment]
Great! I’m glad it was able to be fixed with fairly little effort. Agreed on improving the api generation process as mentioned in https://github.com/Slicer/apidocs.slicer.org/issues/2.

**Comment by lassoan** [comment]
Awesome! Thank you both for working on this.

**Comment by jcfr** [comment]
To follow up on this, the following additional updates have been integrated:
* Transition of to GitHub Actions workflow in both [Slicer/apidocs.slicer.org](https://github.com/Slicer/apidocs.slicer.org) and [Slicer/preview.apidocs.slicer.org](https://github.com/Slicer/preview.apidocs.slicer.org) to respectively `reset` and `squash` the `gh-pages` branch:
  * https://github.com/Slicer/preview.apidocs.slicer.org/commit/884f54b7558fc0939e610e7378e6e28d8ddb6cc6 (`gh-pages-reset: Transition from TravisCI to GitHub action`)
  * https://github.com/Slicer/apidocs.slicer.org/commit/36d0044d97554b697dcb96bae4e78b0e072173f0 (`gh-pages-squash: Transition from TravisCI to GitHub action`)
* Remove of invalid `vmaster` directory from [Slicer/apidocs.slicer.org@gh-pages](https://github.com/Slicer/apidocs.slicer.org/tree/gh-pages)
* Rename of `master` to `main` in [Slicer/preview.apidocs.slicer.org](https://github.com/Slicer/preview.apidocs.slicer.org)
* Update of CircleCI configuration associated with https://app.circleci.com/pipelines/github/Slicer/apidocs.slicer.org . Changed value associated with both `SLICER_REPO_BRANCH` and `SLICER_REPO_REVISION` from `master` to `main`.

**Comment by jcfr** [comment]
Updates:
* [Slicer/github-circleci-trigger](https://github.com/Slicer/github-circleci-trigger): Renamed `master` to `main`
* Migrated the stack used on the heroku instance hosting [Slicer/github-circleci-trigger](https://github.com/Slicer/github-circleci-trigger) application from `cedar-14` to `heroku-22`


<details><summary>Heroku Build log</summary>
<pre>
-----> Building on the Heroku-22 stack
-----> Using buildpack: heroku/python
-----> Python app detected
-----> Using Python version specified in runtime.txt
-----> Stack has changed from cedar-14 to heroku-22, clearing cache
-----> Installing python-3.10.6
-----> Installing pip 22.1.2, setuptools 60.10.0 and wheel 0.37.1
-----> Installing SQLite3
-----> Installing requirements with pip
       Collecting Flask
         Downloading Flask-2.2.2-py3-none-any.whl (101 kB)
       Collecting github-webhook
         Downloading github_webhook-1.0.4-py2.py3-none-any.whl (8.6 kB)
       Collecting ipaddress
         Downloading ipaddress-1.0.23-py2.py3-none-any.whl (18 kB)
       Collecting requests
         Downloading requests-2.28.1-py3-none-any.whl (62 kB)
       Collecting gevent
         Downloading gevent-21.12.0-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (6.1 MB)
       Collecting gunicorn
         Downloading gunicorn-20.1.0-py3-none-any.whl (79 kB)
       Collecting click>=8.0
         Downloading click-8.1.3-py3-none-any.whl (96 kB)
       Collecting Werkzeug>=2.2.2
         Downloading Werkzeug-2.2.2-py3-none-any.whl (232 kB)
       Collecting Jinja2>=3.0
         Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
       Collecting itsdangerous>=2.0
         Downloading itsdangerous-2.1.2-py3-none-any.whl (15 kB)
       Collecting six
         Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
       Collecting certifi>=2017.4.17
         Downloading certifi-2022.6.15-py3-none-any.whl (160 kB)
       Collecting idna<4,>=2.5
         Downloading idna-3.3-py3-none-any.whl (61 kB)
       Collecting charset-normalizer<3,>=2
         Downloading charset_normalizer-2.1.0-py3-none-any.whl (39 kB)
       Collecting urllib3<1.27,>=1.21.1
         Downloading urllib3-1.26.11-py2.py3-none-any.whl (139 kB)
       Collecting zope.event
         Downloading zope.event-4.5.0-py2.py3-none-any.whl (6.8 kB)
       Collecting zope.interface
         Downloading zope.interface-5.4.0.tar.gz (249 kB)
         Preparing metadata (setup.py): started
         Preparing metadata (setup.py): finished with status 'done'
       Collecting greenlet<2.0,>=1.1.0
         Downloading greenlet-1.1.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (155 kB)
       Collecting MarkupSafe>=2.0
         Downloading MarkupSafe-2.1.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
       Building wheels for collected packages: zope.interface
         Building wheel for zope.interface (setup.py): started
         Building wheel for zope.interface (setup.py): finished with status 'done'
         Created wheel for zope.interface: filename=zope.interface-5.4.0-cp310-cp310-linux_x86_64.whl size=210972 sha256=d389a443e0e20fe5e6f6259b4dc1d3f70f73dc0d5d7ee175db65752e892b47bc
         Stored in directory: /tmp/pip-ephem-wheel-cache-n5idz9rj/wheels/21/a9/8b/0bfc5594d8e109d5b25d6b69e0cff14d09d93e3522dcb16d2b
       Successfully built zope.interface
       Installing collected packages: ipaddress, zope.interface, zope.event, urllib3, six, MarkupSafe, itsdangerous, idna, gunicorn, greenlet, click, charset-normalizer, certifi, Werkzeug, requests, Jinja2, gevent, Flask, github-webhook
       Successfully installed Flask-2.2.2 Jinja2-3.1.2 MarkupSafe-2.1.1 Werkzeug-2.2.2 certifi-2022.6.15 charset-normalizer-2.1.0 click-8.1.3 gevent-21.12.0 github-webhook-1.0.4 greenlet-1.1.2 gunicorn-20.1.0 idna-3.3 ipaddress-1.0.23 itsdangerous-2.1.2 requests-2.28.1 six-1.16.0 urllib3-1.26.11 zope.event-4.5.0 zope.interface-5.4.0
-----> Discovering process types
       Procfile declares types -> web
-----> Compressing...
       Done: 29.2M
-----> Launching...
       Released v27
       https://github-circleci-trigger.herokuapp.com/ deployed to Heroku

</pre>
</details>

**Comment by jcfr** [comment]
Following transition of the heroku worker, trigger of documentation build is failing. See https://github.com/Slicer/github-circleci-trigger/issues/4

**Comment by jcfr** [comment]
Updates:
* Issue [Slicer/github-circleci-trigger#4](https://github.com/Slicer/github-circleci-trigger/issues/4) fixed in https://github.com/Slicer/github-circleci-trigger/commit/3cbfd4598502ae836851bd856baebc7aac55e6f8
* URL associated with success status fixed in https://github.com/Slicer/apidocs.slicer.org/commit/7714c1aecba90cda3a3a1a0fa887e6f5111a41f9  (`github.com` -> `github.io`)

**Comment by Sunderlandkyl** [comment]
@jcfr @sjh26
Should we re-open this issue? The API docs are still not updated since 2022.
