### ISSUE TITLE
Mesh subtraction tool for Dynamic Modeler module

### ISSUE THREAD

**Issue by arpinerap** [Slicer/Slicer#5233]
## Is your feature request related to a problem? Please describe.

Dynamic Modeler have a Adding Tool for models. Substraction should be a nice feature too.

## Describe the solution you'd like

New Substraction Tool for Dynamic Modeler Module

## Describe alternatives you've considered

Edit Models Module like Edit Segmentation Module...

## Additional context

Thanks

**Comment by lassoan** [comment]
Boolean mesh operations are now available in "Combine models" module in Sandbox extension. If we get feedback that the feature works well then we'll make the feature available as a new tool in the Dynamic modeler module.

**Comment by arpinerap** [comment]
Thx @lassoan . I´ve tried a bit and find some trouble with it.: 
- The process looks very inestable, Slicer just closes. Substraction operation is the more inestable of all.
- Union and Intersection looks like being crossed, one is really the other.
- Both Difference Operations looks also to be crossed each other.
- There is no option "create a new modes AS.." in the output model selector

**Comment by lassoan** [comment]
> The process looks very inestable, Slicer just closes. Substraction operation is the more inestable of all.

This is not what we see. Could you share the two models that you have problems with?

> Union and Intersection looks like being crossed, one is really the other.
> Both Difference Operations looks also to be crossed each other.

The operations are named correctly. You can verify this by doing the followings: enable developer mode (menu: Edit / Application settings / Developer), restart Slicer, and in Combine models module, click "Reload and test" You can see that each model is what its name says it is. The problem most likely is that one or both of your meshes are turned inside out or have other errors, or maybe the algorithm fails for some other reason. See above, please upload the problematic models somewhere and post the link here.

> There is no option "create a new modes AS.." in the output model selector

The reason for not showing this options is that the output model is generated automatically and you can later rename it using "Rename current model" option. So, you can get a model with the name that you desire with just two clicks (the same as with "Create new model as..." option). Anyway, we can make "Create as..." option visible if users find it confusing.

**Comment by arpinerap** [comment]
> The operations are named correctly. You can verify this by doing the followings: enable developer mode (menu: Edit / Application settings / Developer), restart Slicer, and in Combine models module, click "Reload and test" You can see that each model is what its name says it is. The problem most likely is that one or both of your meshes are turned inside out or have other errors, or maybe the algorithm fails for some other reason

I checked module code before answare you, of course this is not the problem. I agree with you there is some kind of error in source models that library can´t manage properly. Indeed, I tried to fix models with Surface ToolBox (Normals, Clean, etc...) but I didn´t get the solution.


[ModelsToCombine.zip](https://github.com/Slicer/Slicer/files/6003146/ModelsToCombine.zip)

Try to make (Plate - DrillSolid) + DrillHole, for example....

**Comment by lassoan** [comment]
All operations work wonderfully with Plate+DrillHole, without any modifications. Processing takes several minutes, though.

![image](https://user-images.githubusercontent.com/307929/108371228-8d6d9180-71cb-11eb-979b-97a8c2f8a991.png)

![image](https://user-images.githubusercontent.com/307929/108373320-c73f9780-71cd-11eb-9bb5-d4be38be92fc.png)

DrillSolid has extremely ill-shaped triangles at the center of top and bottom. Still subtraction works perfectly:

![image](https://user-images.githubusercontent.com/307929/108373715-31583c80-71ce-11eb-8dc1-901d663629a1.png)

By applying decimation with a factor of 0.8, the processing time is decreased to a few seconds. Since decimation slightly changes the geometry, a few slivers remain after subtraction at the coincident surfaces at the top and bottom. This could be resolved by making the drillhole slightly protrude on both sides of the plate.

I was able to manage to crash the application by applying 0.8 decimation to drillhole and 0.7 to the plate. I'll build the code in debug mode to see if there is any easy way to prevent the crash.

**Comment by lassoan** [comment]
I was able to find the exact cause of this crash and submitted a bug report: https://github.com/zippy84/vtkbool/issues/39.

**Comment by lassoan** [comment]
I've pushed a fix. I'm not sure if it does the right thing but at least there are no crashes.

If you find any crashes in the module in Sandbox extension that you download tomorrow or later then share those models, too, and I'll check if it can be fixed.

**Comment by arpinerap** [comment]
Really fine.... I´ll do some tests with different models after decimation... Thanks again....

**Comment by arpinerap** [comment]
I still have problems witn concatenated operation. Have you tried to make Plate and DrillSolid "difference" and then Result Model with DrillHole "union"? I get always an empty model. I´ve test it in my 2 machines (Win10 both) with same result...

**Comment by lassoan** [comment]
Do you get "Contact ends suddenly at point ..." error? I've already reported that here: https://github.com/zippy84/vtkbool/issues/40

If you upload two models that don't work for you then I'll have a look at it. If it seems different from already known errors then I'll report it to the vtkbool issue tracker.

**Comment by arpinerap** [comment]
> Do you get "Contact ends suddenly at point ..." error? I've already reported that here: zippy84/vtkbool#40

I have no errors in Python Interactor Console. Is there any way to active debug mode for vtk library?

**Comment by lassoan** [comment]
You can find the message in the application log.

**Comment by arpinerap** [comment]
Ok. I have another error message:
`[INFO][Stream] 21.02.2021 18:02:53 [] (unknown:0) - Processing started
[ERROR][VTK] 21.02.2021 18:02:53 [vtkPolyDataBooleanFilter (000001C4FC196EF0)] (D:\D\P\S-0-E-b\Sandbox\CombineModels\Logic\vtkPolyDataBooleanFilter.cxx:214) - Contact ends suddenly at point 2.
[INFO][Stream] 21.02.2021 18:02:53 [] (unknown:0) - Processing completed in 0.22 seconds`

And I share the scene to try your own....


[2021-02-20-Scene.zip](https://github.com/Slicer/Slicer/files/6018132/2021-02-20-Scene.zip)


Thanks....

**Comment by lassoan** [comment]
> Contact ends suddenly at point

Yes, this is the error message that I wrote about above. You can probably fix it by remeshing, for example using https://github.com/pyvista/pyacvd. If you can confirm that it works well then we may bring in acvd remeshing into Slicer.

**Comment by arpinerap** [comment]
I´ve install libraries and I´m trying to apply example:

`slicer.util.pip_install('pyvista')
slicer.util.pip_install('pyacvd')

import pyacvd

models = slicer.mrmlScene.GetNodesByClass('vtkMRMLModelNode')
for model in models:
  model.plot(show_edges=True, color='w')
  clus = pyacvd.Clustering(model)
  clus.subdivide(3)
  clus.cluster(20000)
  clus.plot()
  remesh = clus.create_mesh()
  remesh.plot(color='w', show_edges=True)`

It throw me this error:
`object has no attribute 'plot'`

I´ve also tried: 
`modelMesh = model.GetMesh()`
and
`modelMesh = model.GetMesh().GetCellData()`

**Comment by arpinerap** [comment]
Ok. I delete plot parts but I couldn´t find a working code to go ahead with...

```
slicer.util.pip_install('pyvista')
slicer.util.pip_install('pyacvd')

import pyvista
import pyacvd

models = slicer.mrmlScene.GetNodesByClass('vtkMRMLModelNode')
for model in models:
  modelMesh = model.GetMesh()
  clus = pyacvd.Clustering(modelMesh )
  clus.subdivide(3)
  clus.cluster(20000)
  remesh = clus.create_mesh()
```
It gives me this error y Python Interactor:

```
File "C:\*****\*****\AppData\Local\NA-MIC\Slicer 4.13.0-2021-02-16\lib\Python\Lib\site-packages\pyacvd\clustering.py", line 34, in __init__
    if not mesh.is_all_triangles():
AttributeError: 'vtkCommonDataModelPython.vtkPolyData' object has no attribute 'is_all_triangles'
```

'is_all_triangles' is a method of pyvista.PolyData Grid Class that vtkPolyData doesn´t have. How can convert model mesh to pyvista.PolyData?

**Comment by lassoan** [comment]
Probably pyacvd expects a triangle mesh input. You can run the mesh through a vtkTriangleFilter to convert all polygons to triangles before passing it to pyacvd.

This is how I used pyacvd recently (I did not need triangle filter):

```python
inputFilepath = 'path/to/input.vtk'
outputFilepath = 'path/to/remeshed.vtk'

import pyvista as pv
import pyacvd
mesh = pv.read(inputFilepath)
clus = pyacvd.Clustering(mesh)
# clus.subdivide(2)   # uncomment if mesh is not dense enough for uniform remeshing
clus.cluster(40000)
remesh = clus.create_mesh()
remesh.save(outputFilepath)
slicer.util.loadNodeFromFile(outputFilepath, 'ModelFile', {'coordinateSystem':'ras'})
```

**Comment by arpinerap** [comment]
I get code for vtkTriangleFilter from:
[](https://www.slicer.org/wiki/Documentation/Nightly/ScriptRepository#Export_model_to_Blender.2C_including_color_by_scalar )

```
for model in models:
  modelDisplayNode = model.GetDisplayNode()
  triangles = vtk.vtkTriangleFilter()
  triangles.SetInputConnection(modelDisplayNode.GetOutputPolyDataConnection())
  clus = pyacvd.Clustering(triangles)
  clus.subdivide(3)
  clus.cluster(20000)
  remesh = clus.create_mesh()
```
Gives me error again...
`AttributeError: 'vtkFiltersCorePython.vtkTriangleFilter' object has no attribute 'is_all_triangles'`

**Comment by lassoan** [comment]
For now, read the input from file, as I did in my example above.

**Comment by arpinerap** [comment]
Ok. Remeshing done with read/save files code but fixed models also throw error. First step (difference) is fine but second step (union) gives empty model and this message:
```
[INFO][Stream] 23.02.2021 22:50:29 [] (unknown:0) - Processing started
[CRITICAL][Stream] 23.02.2021 22:50:32 [] (unknown:0) - Contact ends suddenly at point 3573.
[INFO][Stream] 23.02.2021 22:50:32 [] (unknown:0) - Processing completed in 3.78 seconds
```
I´ve also tried to remesh difference model before union operation but it still gives an empty model with same type of error

**Comment by lassoan** [comment]
You can adjust remeshing options.

Just as a test, you can try to translate one of the meshes by 0.01mm and see if it resolves the issue.

**Comment by arpinerap** [comment]
Traslations don´t let me fix the problem, Combine Models Module looks like have some trouble in union operation.
I get some intersting behavior of meshes:
I´ve made two difference models first
![image](https://user-images.githubusercontent.com/16327830/109044860-325c0300-76d3-11eb-9e08-e7f4564e47b9.png)
![image](https://user-images.githubusercontent.com/16327830/109044915-46076980-76d3-11eb-94ea-5fad8b33d8be.png)
Union operation in Combine Models Module couldn´t mix them but Dynamic Modeler throw me this nice object:
![image](https://user-images.githubusercontent.com/16327830/109045196-92eb4000-76d3-11eb-84c5-cfef0a3e207c.png)
New minimalistic scene
[2021-02-20-Scene.zip](https://github.com/Slicer/Slicer/files/6037992/2021-02-20-Scene.zip)

**Comment by lassoan** [comment]
Append tool does not merge the meshes, just puts them next to each other. If they intersect then the resulting mesh is invalid. It does not matter for rendering, but it is not usable for analysis or 3D printing.

You always need to review meshes with Models module -> Display/3D display/Representation->Surface with edges. See just how extremely bad quality the input mesh is:

![image](https://user-images.githubusercontent.com/307929/109213402-866ff180-777e-11eb-9283-82328c6f2a37.png)

The mesh above is only suitable for rendering and is expected to fail when used for any other purpose (processing, analysis, 3D-printing, etc). If we have problems with such bad quality meshes then we cannot report it to vtkbool developer. Either a proper mesh must be be generated (with triangles that have approximately the same side lengths) or these meshes must be remeshed (acvd with significant remeshing could work).

**Comment by arpinerap** [comment]
I´ve tried many things around this issue:
- I change SolidWorks STL export preset with many qualities from here to maximun. Difference operations give better output models and holes between both difference models (previous pictures) are smaller. Normals also are more consistent. I still have problems with Union operations despite better meshes (empty outputs).
- As Union operation throw me empty models, I go to Add operator in Dynamic Modeler as I´ve said to you. @lassoan, as you said, combined model has not closed faces between parts. I look around to MeshMixer and it can be fixed with "Edit/Make Solid" tool. I ´ve found good results wih: "Solid Type": Accurate,  "Solid Accuracy": 300-500 and "Mesh Density": 300-500 parameters.
- Looking for information about how MeshMixer do "Make Solid" operations I found: [https://stackoverflow.com/questions/53512513/python-based-toolbox-for-generating-3d-solid-mesh-based-on-implicit-function](url). Tetrahedralization function should be the way to manage these issues. Maybe PyMesh can be explored [https://pymesh.readthedocs.io/en/latest/api_mesh_generation.html](url). I´ve tried to add it to Slicer but I couldn´t...

**Comment by lassoan** [comment]
>  look around to MeshMixer and it can be fixed with "Edit/Make Solid" tool. I ´ve found good results wih: "Solid Type": Accurate, "Solid Accuracy": 300-500 and "Mesh Density": 300-500 parameters.

That's the same method as Segment Editor's Logical operators effect in Slicer (so, you don't need MeshMixer or pymesh). You can of course always do all Boolean operations correctly by converting meshes to labelmaps and combine the labelmaps, but you lose the original mesh points and you need lots of memory if you want to preserve small details (such as sharp edges or thin surfaces).

**Comment by arpinerap** [comment]
I usually do this method converting models to segments but I need to resample volume as much that computation and memory need goes too high... I´m looking a model way to do the same preserving surface quality with afforable times of process...

**Comment by lassoan** [comment]
Yes, I agree, Boolean operations directly on the meshes is essential for certain use cases, that's why we are working on this feature. I just wanted to highlight that MeshMixer is not a solution for this.

**Comment by arpinerap** [comment]
Sure, To be able to do all tasks in Slicer is important to automate workflows...
Is there any way to add PyMesh library to Slicer to probe it as I did with pyacvd?

**Comment by lassoan** [comment]
You can install any Python packages in Slicer that have binary packages (wheels). Packages that do not have wheels are usually low-quality, not-well-maintained packages.

If you have trouble installing PyMesh (e.g., it tries to build something) then it means that there are no wheels. It would not be surprising, because PyMesh looks like a mess - a heap of various libraries hobbled into a Python package. PyMesh also include GPL code, such as CGAL, so I would not recommend using PyMesh.

We could try directly using Boolean mesh libraries, instead of going through PyMesh. 
- CGAL: irrelevant (GPL license)
- [Cork](https://github.com/gilbo/cork): LGPL license, it may worth a try, but there are red flags. 1 PyMesh works with 4 other Boolean mesh libraries indicates that Cork does not work clearly better than the others (which we know are not work very robustly). 2. https://github.com/gilbo/cork is unmaintained, there are a few forks, but not with much activity either.
- Carve: "has it's own limitations and cases when it will fail and produce incorrect results. It is also very slow" (https://blender.stackexchange.com/questions/93515/boolean-modifier-carve-vs-bmesh-solver). We used this in early Blender versions and indeed it was very unreliable.
- Clipper: irrelevant (2D only)
- libigl: irrelevant (only a wrapper over Cork and CGAL)

There are some other options dicussed [here])(https://github.com/mikedh/trimesh/issues/938).

In general, the situation seems pretty bad. All Boolean mesh libraries are quite fragile and some of them are also very slow.

At least with vtkbool there is someone to talk to, who can give advice and fix issues.

**Comment by lassoan** [comment]
Developer of vtkbool made some fixes and improvements. They will be available in Sandbox extension tomorrow. Please test. You need to use latest stable or preview release to get the update.

**Comment by arpinerap** [comment]
Empty model again...
[ERROR][VTK] 06.03.2021 10:56:42 [vtkPolyDataBooleanFilter (00000217001BAC20)] (D:\D\P\S-0-E-b\Sandbox\CombineModels\Logic\vtkPolyDataBooleanFilter.cxx:214) - Contact ends suddenly at point 27.

**Comment by lassoan** [comment]
You haven't used the latest version of the extension. If you update now then you will get the latest version. It works perfectly on these tubes.

**Comment by arpinerap** [comment]
Ok. Union operation between Diff and Diff1 is fixed. 
Other Union operations like Diff + Tube1 throw empty models:
![image](https://user-images.githubusercontent.com/16327830/110254822-1e48b900-7f91-11eb-999c-66f2e45b9e81.png)
[ERROR][VTK] 07.03.2021 22:02:38 [vtkPolyDataBooleanFilter (000001C6E551C360)] (D:\D\P\S-0-E-b\Sandbox\CombineModels\Logic\vtkPolyDataBooleanFilter.cxx:214) - Contact ends suddenly at point 652.

**Comment by lassoan** [comment]
Thanks for the example.

Computing union of Diff and Tube1 is not a realistic task, because the meshes have tons of coincident faces and they are all extremely ill-shaped. You need to mesh the inputs properly (those sliver triangles are suitable for rendering but not for mesh operations) or also resolve coincident faces by applying minimum amount of translation or scaling to make the meshes properly overlap (but the best is to fix both the sliver elements and make the meshes overlap robustly).

If you find any meaningful task that the algorithm fails to accomplish then we can report it to developer of vtkbool, but I don't think we can expect this specific union computation to succeed.

**Comment by lassoan** [comment]
It seems that we cannot do much right now about this in Slicer core, therefore I'm closing this.
