### ISSUE TITLE
Slicer module build failing due to Slicer's CMake not getting correct paths

### ISSUE THREAD

**Issue by jhlegarreta** [Slicer/Slicer#7137]
## Summary

Building `SlicerDMRI` in a GHA workflow CI with some custom paths
https://github.com/jhlegarreta/SlicerDMRI/actions/runs/5707614346/job/15464465415#step:7:7

defined in here:
https://github.com/jhlegarreta/SlicerDMRI/actions/runs/5707614346/job/15464465415#step:7:19

seems to make the module at issue build fail because a given file cannot be copied (as the source path does not exist):
https://github.com/jhlegarreta/SlicerDMRI/actions/runs/5707614346/job/15464465415#step:7:240

Although the failure message is not very informative, I'd say that the file at issue `NsgPlanTracto.py` does not exist in here:
```
/home/runner/work/SlicerDMRI/SlicerDMRI//Modules/Loadable/TractographyDisplay/Testing/Python/NsgPlanTracto.py
```

As the checkout path is
```
/home/runner/work/SlicerDMRI/SlicerDMRI/../../slicerdmri-src
```

The macro call in the module is in:
https://github.com/SlicerDMRI/SlicerDMRI/blob/610533480896d2884cb9ab0671c88874d237247d/Modules/Loadable/TractographyDisplay/Testing/Python/CMakeLists.txt#L5C1-L5C1

And the macro is defined in Slicer in:
https://github.com/Slicer/Slicer/blob/968fd241328d3a7b6d5fe632b32db863aabcf90c/CMake/SlicerMacroBuildScriptedModule.cmake#L21

So I guess there is some CMake variable (like the binary dir) missing somewhere in the macro, or some assumption is being made about the paths that does not hold.

## Steps to reproduce

1. Clone Slicer (HEAD revision as of 2023-07-30, 968fd241328d3a7b6d5fe632b32db863aabcf90c).
1. Configure and build Slicer.
1. Clone `SlicerDMRI` to a specific folder; create a directory for the build, and change directory there.
1. Configure and build `SlicerDMRI`.

## Expected behavior

`SlicerDMRI` (or any other remote module) builds correctly when using custom paths for the sources.

## Environment
- Slicer version: `HEAD` (e.g. as of 2023-07-30, 968fd241328d3a7b6d5fe632b32db863aabcf90c).
- Operating system: Ubuntu 22.04.2 LTS

**Comment by lassoan** [comment]
The first while I see it's `Dependent extension UKFTractography cannot be found by CMake`. All other errors may be a consequence of this, so before doing anything else, this error should be fixed (build the dependence and set ..._DIR CMake variable).

Is there a specific reason you are using ninja? Was there an example your followed? I would recommend to get started by following the build instructions in the Slicer documentation and once everything works you can experiment with new ways of building (to see if you can improve some aspects).

Have your found that you need to set all those directories? Normally all you need to set is Slicer_DIR.

**Comment by lassoan** [comment]
> Not sure that the rest of the errors are a consequence of this; in that case, why is it a warning instead of an error?

This message is reported by the extension build system. Some extension may declare optional dependencies here, which would still allow the extension to build, so it may be useful to allow the build to proceed.

> gcc was way slower/timing out.

Interesting. Hopefully we'll find a way to get a fast enough builds without supporting several different build toolsets. Providing support for multiple ways to build Slicer (one simpler and one faster) could be significant extra workload.

> For example, I could not follow the Qt recipe because the current instructions require launching an interactive installer that cannot be bypassed with a --yes flag AFAIK

You can follow the instruction, do all the necessary confirmations interactively in the docker container, and then `docker commit` to save the result into a new image that you can then use as a basis in all automated CI work. Qt version in Slicer is changed so rarely (not more frequently than once a year) that updating the base image manually would not be a problem. But you can also just skip this step and use the `slicer/slicer-base` image in dockerhub. We considered building using the base image an advanced topic (that we can recommend to advanced users when they need it), but maybe we should add it to the build instructions?

> I am only setting the source and build dirs, Qt5_DIR and Slicer_DIR, nothing else

I see, OK, I thought all the directories that [appeared in the build action](https://github.com/jhlegarreta/SlicerDMRI/actions/runs/5707614346/job/15464465415#step:7:7) were inputs that you provided but they were just outputs. It is all good then.

**Comment by jhlegarreta** [comment]
> You can follow the instruction, do all the necessary confirmations interactively in the docker container, 

For now, as said, I prefer not to use a Docker container, and try to get a minimal working build, and help clean some aspects.

**Comment by jhlegarreta** [comment]
My workaround in https://github.com/SlicerDMRI/SlicerDMRI/commit/aba80ee2f87274e77bcb84410c399f9a01f046fb for the time being to get things working was to avoid using relative paths, or variables containing relative paths when checking out `SlicerDMRI`; https://github.com/SlicerDMRI/SlicerDMRI/pull/177 does not strictly address this; it only leverages the previous workaround. So unfortunately, I do not think we can say the issue is solved.

**Comment by jcfr** [comment]
I had another look and  he updated workflow fixes the actual issue.

## Observation

As you can see in the log, the path ends up including the string `$SLICER_DMRI_SRC_REL_DIR`.

This is not expected, it should have been resolved already.


<img width=75% src="https://github.com/Slicer/Slicer/assets/219043/c583a739-3fca-4f55-b376-aac9c058c59f"/>

## Source

This should have been resolved to the expected value. 

It likely happened because in https://github.com/jhlegarreta/SlicerDMRI/commit/67e378d29b7329436effecf0be1e09b17fadce57, you intended to concatenate two env. variables:

<img width=75% src="https://github.com/Slicer/Slicer/assets/219043/6441c5f8-bf83-4a8f-a5a8-fc4b93a19052"/>

I think you should have use  the following syntax:

```
${{ github.workspace }}/${{ env.SLICER_DMRI_SRC_REL_DIR }}`
```

That said, I am not event sure that works at that level because the `env' object has not been updated.

**Comment by jhlegarreta** [comment]
:+1: Maybe `${{ github.workspace }}/${{ env.SLICER_DMRI_SRC_REL_DIR }}` would have made the trick, but I still cannot understand why all the rest of the steps in the `SlicerDMRI` check out and config process did not fail, and it was only copying a Python file in that was failing. As said, in the updated workflow I chose to get away without using relative paths, and hence subsequent runs have been successful as this has been adopted. But I am fine with the current approach, it is clean enough.
